# ui/theme.py
import customtkinter as ctk

# Premium Glassmorphic Theme Palette Colors (Light, Dark)
THEME_BG = ("#f1f5f9", "#090d16")                 # Soft Slate-Blue / Deep Space Obsidian
THEME_CARD_BG = ("#ffffff", "#121b2d")             # Translucent white glass / Deep Slate card glass
THEME_CARD_BORDER = ("#cbd5e1", "#22334f")         # Soft borders / Glass glow border
THEME_TEXT_PRIMARY = ("#0f172a", "#f8fafc")        # Title / strong text
THEME_TEXT_SECONDARY = ("#475569", "#94a3b8")      # Muted body text
THEME_ACCENT_BLUE = ("#2563eb", "#00d2ff")         # Accent cyan/blue
THEME_ACCENT_INDIGO = ("#4f46e5", "#6366f1")       # Violet-Indigo main
THEME_ACCENT_GREEN = ("#16a34a", "#10b981")        # Success states
THEME_ACCENT_RED = ("#dc2626", "#f43f5e")          # Error/Cancel states
THEME_CARD_SUBTITLE = ("#64748b", "#38bdf8")

TRANSLATIONS = {
    "en": {
        "title": "yt-dlp Downloader Pro",
        "subtitle": "Smart multi-video and audio download manager with semi-translucent glassmorphic depth.",
        "theme_light": "☀️ Light Mode",
        "theme_dark": "🌙 Dark Mode",
        "url_label": "Video / Playlist Address",
        "paste_btn": "📋 Paste from Clipboard",
        "batch_switch": "Batch List Mode",
        "url_placeholder": "Paste your YouTube, Vimeo, SoundCloud or other video links here...",
        "save_folder_label": "Output Folder Location",
        "browse_btn": "📂 Choose Folder",
        "preset_label": "Quick Download Format Profile",
        "preset_best": "🚀 Best Quality\n(Max Video & Audio)",
        "preset_1080p": "📺 Full HD 1080p\n(Balanced MP4)",
        "preset_720p": "⚡ Balanced Fast\n(Speedy 720p)",
        "preset_mp3": "🎵 High Quality Audio\n(320kbps MP3 Müzik)",
        "active_profile_best": "Active Profile: 🚀 Best Resolution (Maximum video quality and audio)",
        "active_profile_1080p": "Active Profile: 📺 Full HD 1080p limited video (AAC/MP4 encoding)",
        "active_profile_720p": "Active Profile: ⚡ Speedy 720p download (Balanced file size)",
        "active_profile_audio": "Active Profile: 🎵 High Quality Audio ({format} - {quality})",
        "active_profile_custom": "Active Profile: Custom formats selected via advanced panel.",
        "queue_label": "Download Queue & Manager",
        "add_queue_btn": "➕ Add to Queue",
        "queue_placeholder": "No videos in download queue. Add links from above.",
        "advanced_toggle": "Show Advanced Download & File Settings",
        "advanced_hint": "(Resolution, codec formats, cookies, speed limits and extra yt-dlp arguments)",
        "tab_codecs": "Resolution & Codec",
        "tab_limits": "Limits & Cookies",
        "tab_flags": "Permissions",
        "tab_clip": "Time Clip ✂️",
        "lbl_clip_enable": "Enable Time Clipping",
        "lbl_clip_start": "Start Time (MM:SS or Secs):",
        "lbl_clip_end": "End Time (MM:SS or Secs):",
        "lbl_clip_precise": "Precise Cut (Slow re-encode)",
        "lbl_mode": "Download Mode:",
        "lbl_profile": "Quality Profile:",
        "lbl_max_res": "Max Resolution:",
        "lbl_format": "Video Format:",
        "lbl_audio_ext": "Audio Extension:",
        "lbl_audio_qual": "Audio Quality:",
        "lbl_audio_codec": "Audio Codec (Video):",
        "lbl_playlist_range": "Playlist Range:",
        "lbl_max_dl": "Max Downloads:",
        "lbl_speed_limit": "Speed Limit:",
        "lbl_cookie_file": "Cookie File (.txt):",
        "lbl_browser_cookie": "Browser Cookies:",
        "lbl_retry": "Retry Counts:",
        "lbl_concurrent": "Concurrent Fragments:",
        "lbl_header_addons": "Media Add-ons",
        "chk_thumb": "Download Visual (Thumbnail)",
        "chk_subs": "Download Subtitle Files",
        "chk_auto_subs": "Auto Translation Subtitles",
        "lbl_header_behavior": "Download Behaviors",
        "chk_playlist": "Process as Playlist",
        "chk_metadata": "Add Metadata Tags",
        "chk_restrict_names": "Clean Filenames (Safe Characters)",
        "chk_archive": "Use Download Archive (Skip existing)",
        "chk_youtube_403": "TV Client Fallback on YouTube 403",
        "chk_sponsorblock": "SponsorBlock (Cut sponsor segments)",
        "lbl_template": "Filename Template:",
        "btn_update": "🔄 Update yt-dlp",
        "lbl_extra_params": "Extra Parameters:",
        "lbl_dashboard_title": "Active Download Progress Panel",
        "lbl_active_dl": "Currently Downloading: Idle",
        "lbl_speed": "Download Speed",
        "lbl_eta": "Remaining Time (ETA)",
        "lbl_size": "Total File Size",
        "btn_start": "🚀 Start Downloads",
        "btn_cancel": "🛑 Cancel",
        "btn_clear": "🧹 Clear Logs",
        "btn_open_folder": "📂 Open Folder",
        "lbl_status_ready": "Ready (Waiting)",
        "lbl_status_pasted": "URL Pasted from Clipboard",
        "lbl_status_added": "Added {count} new downloads to queue",
        "lbl_status_processing": "Processing Queue ({curr}/{total})...",
        "lbl_status_cancelled": "Download Queue Process Cancelled",
        "lbl_status_completed": "All Downloads Completed!",
        "lbl_status_active_dl": "Currently Downloading: {title}",
        "lbl_preview_loading": "Fetching video info, please wait...",
        "lbl_preview_title": "Video Title Loading...",
        "lbl_preview_author": "Channel Name",
        "lbl_preview_dur": "Duration: --:--",
        "lbl_preview_err": "Failed to fetch video details (Unsupported URL or no internet).",
        "lbl_toast_success_title": "Download Successful!",
        "lbl_toast_success_desc": "'{title}' successfully downloaded.",
        "lbl_toast_err_title": "Download Failed",
        "lbl_toast_err_desc": "Error code {code} - '{title}'",
        "lbl_toast_all_title": "All Tasks Completed!",
        "lbl_toast_all_desc": "All queued videos successfully downloaded.",
        "lbl_logs_toggle": "Show Advanced System and Terminal Logs",
        "lbl_toast_update_title": "Update Successful",
        "lbl_toast_update_desc": "yt-dlp packages updated to the latest version!",
        "lbl_placeholder_range": "Ex: 1-10, 15",
        "lbl_placeholder_max": "Ex: 5",
        "lbl_placeholder_speed": "Ex: 2M or 500K",
        "lbl_placeholder_cookies": "Select text file...",
        "lbl_placeholder_retry": "Ex: 10",
        "lbl_placeholder_fragments": "Ex: 4",
        "lbl_placeholder_extra": "Ex: --sleep-interval 1",
        "lbl_queue_item_placeholder": "Queue empty. Add links above to download.",
        "lbl_queue_remove": "❌ Remove",
        "lbl_dialog_close_title": "Exit",
        "lbl_dialog_close_desc": "Downloads are in progress. Are you sure you want to exit?",
        "lbl_dialog_deps_title": "Missing Packages",
        "lbl_dialog_deps_desc": "yt-dlp is not installed.\nTerminal: pip install -r requirements.txt",
        "lbl_dialog_err_title": "Invalid Value",
        "lbl_dialog_err_digit": "{field_name} must be a number.",
        "lbl_dialog_err_min": "{field_name} must be at least {min_value}.",
        "lbl_dialog_err_template": "Filename template cannot be empty.",
        "lbl_dialog_info_title": "Information",
        "lbl_dialog_info_running": "Downloads are already in progress.",
        "lbl_dialog_warning_title": "Missing Info",
        "lbl_dialog_warning_url": "Please enter a valid URL.",
        "preview_name_label": "Output Filename Preview: {preview}",
        "tab_active": "Active Queue 📋",
        "tab_history": "History 📁",
        "btn_redownload": "🔄 Re-download",
        "lbl_preset_action": "Preset Profiles",
        "btn_save_preset": "💾 Save Preset",
        "btn_delete_preset": "❌ Delete",
        "lbl_toast_outdated_title": "Update Warning",
        "lbl_toast_outdated_desc": "Your yt-dlp version is more than 90 days old! Updating on startup is recommended."
    },
    "tr": {
        "title": "yt-dlp Downloader Pro",
        "subtitle": "Yarı saydam glassmorphic derinlik ile akıllı çoklu video ve ses indirme yöneticisi.",
        "theme_light": "☀️ Aydınlık Mod",
        "theme_dark": "🌙 Karanlık Mod",
        "url_label": "Video / Playlist Adresi",
        "paste_btn": "📋 Panodan Yapıştır",
        "batch_switch": "Çoklu Liste Modu",
        "url_placeholder": "Kopyaladığınız YouTube, Vimeo, SoundCloud veya diğer video linklerini buraya ekleyin...",
        "save_folder_label": "İndirilen Dosyaların Kaydedileceği Klasör",
        "browse_btn": "📂 Klasör Seç",
        "preset_label": "Hızlı İndirme Format Profili",
        "preset_best": "🚀 En İyi Kalite\n(Maksimum Görüntü & Ses)",
        "preset_1080p": "📺 Full HD 1080p\n(Dengeli Standart MP4)",
        "preset_720p": "⚡ Dengeli Fast\n(Hızlı 720p İndirme)",
        "preset_mp3": "🎵 Yüksek Kalite Ses\n(320kbps MP3 Müzik)",
        "active_profile_best": "Aktif Profil: 🚀 En İyi Çözünürlük (Maksimum video kalitesi ve ses kodeği)",
        "active_profile_1080p": "Aktif Profil: 📺 Full HD 1080p limitli video (AAC/MP4 kodlama)",
        "active_profile_720p": "Aktif Profil: ⚡ Hızlı 720p indirme (Dengeli dosya boyutu)",
        "active_profile_audio": "Aktif Profil: 🎵 Yüksek Kalite Ses çıkışı ({format} - {quality})",
        "active_profile_custom": "Aktif Profil: Gelişmiş panel üzerinden özel format seçildi.",
        "queue_label": "İndirme Sırası ve Kuyruk Yöneticisi",
        "add_queue_btn": "➕ Kuyruğa Ekle",
        "queue_placeholder": "Kuyrukta indirilecek video bulunmuyor. Yukarıdan video ekleyin.",
        "advanced_toggle": "Gelişmiş İndirme ve Dosya Ayarlarını Göster",
        "advanced_hint": "(Çözünürlük, codec formatları, çerezler, hız sınırları ve ekstra yt-dlp argümanları)",
        "tab_codecs": "Çözünürlük & Codec",
        "tab_limits": "Limitler & Çerezler",
        "tab_flags": "İzinler",
        "tab_clip": "Kırp ✂️",
        "lbl_clip_enable": "Zaman Aralığını Kırpmayı Etkinleştir",
        "lbl_clip_start": "Başlangıç Zamanı (DK:SN veya Saniye):",
        "lbl_clip_end": "Bitiş Zamanı (DK:SN veya Saniye):",
        "lbl_clip_precise": "Hassas Kesim (Yavaş yeniden kodlama)",
        "lbl_mode": "İndirme Modu:",
        "lbl_profile": "Kalite Profili:",
        "lbl_max_res": "Maks. Çözünürlük:",
        "lbl_format": "Video Formatı:",
        "lbl_audio_ext": "Ses Uzantısı:",
        "lbl_audio_qual": "Ses Kalitesi:",
        "lbl_audio_codec": "Ses Kodeği (Video):",
        "lbl_playlist_range": "Oynatma Listesi Aralığı:",
        "lbl_max_dl": "Maks. İndirme:",
        "lbl_speed_limit": "Hız Limiti:",
        "lbl_cookie_file": "Çerez Dosyası (.txt):",
        "lbl_browser_cookie": "Tarayıcı Çerezleri:",
        "lbl_retry": "Tekrar Deneme Sayısı:",
        "lbl_concurrent": "Eşzamanlı Parçacık:",
        "lbl_header_addons": "Ek Donanımlar",
        "chk_thumb": "Görseli İndir (Küçük Resim)",
        "chk_subs": "Altyazı Dosyalarını İndir",
        "chk_auto_subs": "Otomatik Çeviri Altyazıları",
        "lbl_header_behavior": "İndirme Davranışları",
        "chk_playlist": "Oynatma Listesi Olarak İşle",
        "chk_metadata": "Metadata Etiketlerini Ekle",
        "chk_restrict_names": "Dosya İsimlerini Temizle (Güvenli Karakterler)",
        "chk_archive": "İndirme Arşivi Kullan (Önceden inenleri atla)",
        "chk_youtube_403": "YouTube 403 Hatasında TV İstemcisine Geç",
        "chk_sponsorblock": "SponsorBlock (Sponsor bölümlerini otomatik kes)",
        "lbl_template": "Dosya Adı Şablonu:",
        "btn_update": "🔄 yt-dlp Güncelle",
        "lbl_extra_params": "Ekstra Parametreler:",
        "lbl_dashboard_title": "Aktif İndirme İlerleme Paneli",
        "lbl_active_dl": "Şu Anda İndirilen: Beklemede",
        "lbl_speed": "İndirme Hızı",
        "lbl_eta": "Kalan Süre (ETA)",
        "lbl_size": "Toplam Dosya Boyutu",
        "btn_start": "🚀 İndirmeleri Başlat",
        "btn_cancel": "🛑 İptal Et",
        "btn_clear": "🧹 Günlükleri Temizle",
        "btn_open_folder": "📂 Klasörü Aç",
        "lbl_status_ready": "Hazır (Bekliyor)",
        "lbl_status_pasted": "Adres Panodan Yapıştırıldı",
        "lbl_status_added": "Kuyruğa {count} yeni indirme eklendi",
        "lbl_status_processing": "Kuyruk İşleniyor ({curr}/{total})...",
        "lbl_status_cancelled": "İndirme Sırası İşlemi İptal Edildi",
        "lbl_status_completed": "Tüm İndirmeler Tamamlandı!",
        "lbl_status_active_dl": "Şu Anda İndirilen: {title}",
        "lbl_preview_loading": "Video bilgileri alınıyor, lütfen bekleyin...",
        "lbl_preview_title": "Video Başlığı Yükleniyor...",
        "lbl_preview_author": "Kanal Adı",
        "lbl_preview_dur": "Süre: --:--",
        "lbl_preview_err": "Video detayları alınamadı (Desteklenmeyen URL veya internet yok).",
        "lbl_toast_success_title": "İndirme Başarılı!",
        "lbl_toast_success_desc": "'{title}' başarıyla indirildi.",
        "lbl_toast_err_title": "İndirme Başarısız",
        "lbl_toast_err_desc": "Hata kodu {code} - '{title}'",
        "lbl_toast_all_title": "Tüm Görevler Tamamlandı!",
        "lbl_toast_all_desc": "Kuyruktaki tüm videolar başarıyla indirildi.",
        "lbl_logs_toggle": "Gelişmiş Sistem ve Terminal Günlüklerini Göster",
        "lbl_toast_update_title": "Güncelleme Başarılı",
        "lbl_toast_update_desc": "yt-dlp paketleri en son sürüme güncellendi!",
        "lbl_placeholder_range": "Örn: 1-10, 15",
        "lbl_placeholder_max": "Örn: 5",
        "lbl_placeholder_speed": "Örn: 2M veya 500K",
        "lbl_placeholder_cookies": "Metin dosyası seçin...",
        "lbl_placeholder_retry": "Örn: 10",
        "lbl_placeholder_fragments": "Örn: 4",
        "lbl_placeholder_extra": "Örn: --sleep-interval 1",
        "lbl_queue_item_placeholder": "Kuyruk boş. İndirmek için yukarıdan link ekleyin.",
        "lbl_queue_remove": "❌ Kaldır",
        "lbl_dialog_close_title": "Çıkış",
        "lbl_dialog_close_desc": "Devam eden indirmeler bulunuyor. Çıkmak istediğinize emin misiniz?",
        "lbl_dialog_deps_title": "Eksik Paketler",
        "lbl_dialog_deps_desc": "yt-dlp yüklü değil.\nTerminal: pip install -r requirements.txt",
        "lbl_dialog_err_title": "Geçersiz Değer",
        "lbl_dialog_err_digit": "{field_name} bir sayı olmalıdır.",
        "lbl_dialog_err_min": "{field_name} en az {min_value} olmalıdır.",
        "lbl_dialog_err_template": "Dosya adı şablonu boş olamaz.",
        "lbl_dialog_info_title": "Bilgi",
        "lbl_dialog_info_running": "İndirme işlemleri zaten devam ediyor.",
        "lbl_dialog_warning_title": "Eksik Bilgi",
        "lbl_dialog_warning_url": "Lütfen geçerli bir URL girin.",
        "preview_name_label": "Çıktı Dosya Adı Önizleme: {preview}",
        "tab_active": "Aktif Kuyruk 📋",
        "tab_history": "Geçmiş 📁",
        "btn_redownload": "🔄 Tekrar İndir",
        "lbl_preset_action": "Hazır Profil Şablonları",
        "btn_save_preset": "💾 Profili Kaydet",
        "btn_delete_preset": "❌ Sil",
        "lbl_toast_outdated_title": "Güncelleme Uyarısı",
        "lbl_toast_outdated_desc": "yt-dlp sürümünüz 90 günden eski! Açılışta güncellemeniz önerilir."
    },
    "es": {
        "title": "yt-dlp Downloader Pro",
        "subtitle": "Gestor inteligente de descargas de múltiples videos y audio con profundidad glassmorphic translúcida.",
        "theme_light": "☀️ Modo Claro",
        "theme_dark": "🌙 Modo Oscuro",
        "url_label": "Dirección de Video / Playlist",
        "paste_btn": "📋 Pegar desde Portapapeles",
        "batch_switch": "Modo de Lista Múltiple",
        "url_placeholder": "Pegue aquí los enlaces de YouTube, Vimeo, SoundCloud u otros videos...",
        "save_folder_label": "Carpeta de Guardado",
        "browse_btn": "📂 Seleccionar Carpeta",
        "preset_label": "Perfil de Formato de Descarga Rápida",
        "preset_best": "🚀 Mejor Calidad\n(Máximo Video y Audio)",
        "preset_1080p": "📺 Full HD 1080p\n(MP4 Estándar Equilibrado)",
        "preset_720p": "⚡ Rápido Equilibrado\n(Descarga Rápida a 720p)",
        "preset_mp3": "🎵 Audio de Alta Calidad\n(Música MP3 a 320kbps)",
        "active_profile_best": "Perfil Activo: 🚀 Mejor resolución (Máxima calidad de video y códec de audio)",
        "active_profile_1080p": "Perfil Activo: 📺 Video Full HD 1080p limitado (Codificación AAC/MP4)",
        "active_profile_720p": "Perfil Activo: ⚡ Descarga rápida a 720p (Tamaño de archivo equilibrado)",
        "active_profile_audio": "Perfil Activo: 🎵 Audio de alta calidad ({format} - {quality})",
        "active_profile_custom": "Perfil Activo: Formato personalizado seleccionado mediante el panel avanzado.",
        "queue_label": "Cola de Descargas y Gestor",
        "add_queue_btn": "➕ Añadir a la Cola",
        "queue_placeholder": "No hay videos en la cola de descarga. Añada enlaces arriba.",
        "advanced_toggle": "Mostrar Configuración Avanzada de Archivos y Descarga",
        "advanced_hint": "(Resolución, formatos de códec, cookies, límites de velocidad y argumentos adicionales de yt-dlp)",
        "tab_codecs": "Resolución y Códec",
        "tab_limits": "Límites y Cookies",
        "tab_flags": "Permisos",
        "tab_clip": "Recortar ✂️",
        "lbl_clip_enable": "Habilitar Recorte de Tiempo",
        "lbl_clip_start": "Tiempo de Inicio (MM:SS o Segs):",
        "lbl_clip_end": "Tiempo de Finalización (MM:SS o Segs):",
        "lbl_clip_precise": "Corte Preciso (Recodificación lenta)",
        "lbl_mode": "Modo de Descarga:",
        "lbl_profile": "Perfil de Calidad:",
        "lbl_max_res": "Max Resolución:",
        "lbl_format": "Formato de Video:",
        "lbl_audio_ext": "Extensión de Audio:",
        "lbl_audio_qual": "Calidad de Audio:",
        "lbl_audio_codec": "Códec de Audio (Video):",
        "lbl_playlist_range": "Rango de Playlist:",
        "lbl_max_dl": "Descargas Máximas:",
        "lbl_speed_limit": "Límite de Velocidad:",
        "lbl_cookie_file": "Archivo de Cookies (.txt):",
        "lbl_browser_cookie": "Cookies del Navegador:",
        "lbl_retry": "Reintentos:",
        "lbl_concurrent": "Fragmentos Simultáneos:",
        "lbl_header_addons": "Complementos de Medios",
        "chk_thumb": "Descargar Imagen (Miniatura)",
        "chk_subs": "Descargar Archivos de Subtítulos",
        "chk_auto_subs": "Subtítulos de Traducción Automática",
        "lbl_header_behavior": "Comportamientos de Descarga",
        "chk_playlist": "Procesar como Lista de Reproducción",
        "chk_metadata": "Añadir Etiquetas de Metadatos",
        "chk_restrict_names": "Nombres de Archivo Limpios (Caracteres seguros)",
        "chk_archive": "Usar Archivo de Descargas (Omitir existentes)",
        "chk_youtube_403": "Alternar Cliente de TV al error YouTube 403",
        "chk_sponsorblock": "SponsorBlock (Cortar segmentos de patrocinador)",
        "lbl_template": "Plantilla de Nombre de Archivo:",
        "btn_update": "🔄 Actualizar yt-dlp",
        "lbl_extra_params": "Parámetros Adicionales:",
        "lbl_dashboard_title": "Panel de Progreso de Descarga Activa",
        "lbl_active_dl": "Descargando actualmente: Inactivo",
        "lbl_speed": "Velocidad de Descarga",
        "lbl_eta": "Tiempo Restante (ETA)",
        "lbl_size": "Tamaño Total del Archivo",
        "btn_start": "🚀 Iniciar Descargas",
        "btn_cancel": "🛑 Cancelar",
        "btn_clear": "🧹 Limpiar Registros",
        "btn_open_folder": "📂 Abrir Carpeta",
        "lbl_status_ready": "Listo (Esperando)",
        "lbl_status_pasted": "Dirección Pegada del Portapapeles",
        "lbl_status_added": "Se agregaron {count} nuevas descargas a la cola",
        "lbl_status_processing": "Procesando Cola ({curr}/{total})...",
        "lbl_status_cancelled": "Proceso de Cola de Descargas Cancelado",
        "lbl_status_completed": "¡Todas las descargas completadas!",
        "lbl_status_active_dl": "Descargando actualmente: {title}",
        "lbl_preview_loading": "Obteniendo información del video, espere...",
        "lbl_preview_title": "Cargando título del video...",
        "lbl_preview_author": "Nombre del canal",
        "lbl_preview_dur": "Duración: --:--",
        "lbl_preview_err": "Error al obtener detalles del video (URL no compatible o sin internet).",
        "lbl_toast_success_title": "¡Descarga Exitosa!",
        "lbl_toast_success_desc": "'{title}' descargado con éxito.",
        "lbl_toast_err_title": "Descarga Fallida",
        "lbl_toast_err_desc": "Código de error {code} - '{title}'",
        "lbl_toast_all_title": "¡Todas las tareas completadas!",
        "lbl_toast_all_desc": "Todos los videos en cola se descargaron con éxito.",
        "lbl_logs_toggle": "Mostrar registros avanzados del sistema y del terminal",
        "lbl_toast_update_title": "Actualización Exitosa",
        "lbl_toast_update_desc": "¡Paquetes de yt-dlp actualizados a la última versión!",
        "lbl_placeholder_range": "Ej: 1-10, 15",
        "lbl_placeholder_max": "Ej: 5",
        "lbl_placeholder_speed": "Ej: 2M o 500K",
        "lbl_placeholder_cookies": "Seleccionar archivo de texto...",
        "lbl_placeholder_retry": "Ej: 10",
        "lbl_placeholder_fragments": "Ej: 4",
        "lbl_placeholder_extra": "Ej: --sleep-interval 1",
        "lbl_queue_item_placeholder": "Cola vacía. Agregue enlaces arriba para descargar.",
        "lbl_queue_remove": "❌ Eliminar",
        "lbl_dialog_close_title": "Salir",
        "lbl_dialog_close_desc": "Las descargas están en curso. ¿Está seguro de que desea salir?",
        "lbl_dialog_deps_title": "Paquetes Faltantes",
        "lbl_dialog_deps_desc": "yt-dlp no está instalado.\nTerminal: pip install -r requirements.txt",
        "lbl_dialog_err_title": "Valor No Válido",
        "lbl_dialog_err_digit": "{field_name} debe ser un número.",
        "lbl_dialog_err_min": "{field_name} debe ser al menos {min_value}.",
        "lbl_dialog_err_template": "La plantilla de nombre de archivo no puede estar vacía.",
        "lbl_dialog_info_title": "Información",
        "lbl_dialog_info_running": "Las descargas ya están en curso.",
        "lbl_dialog_warning_title": "Información Faltante",
        "lbl_dialog_warning_url": "Por favor, introduzca una URL válida.",
        "preview_name_label": "Vista Previa del Archivo: {preview}",
        "tab_active": "Cola Activa 📋",
        "tab_history": "Historial 📁",
        "btn_redownload": "🔄 Redescargar",
        "lbl_preset_action": "Perfiles Predefinidos",
        "btn_save_preset": "💾 Guardar Perfil",
        "btn_delete_preset": "❌ Eliminar",
        "lbl_toast_outdated_title": "Advertencia de Actualización",
        "lbl_toast_outdated_desc": "¡La versión de yt-dlp tiene más de 90 días de antigüedad! Se recomienda actualizar al iniciar."
    }
}
